[target.'cfg(all(target_arch = "arm", target_os = "none"))']
runner = "probe-rs run --chip STM32H723ZGTx --probe 0483:374e:0043002C3039510734393838"

[build]
target = "thumbv7em-none-eabihf"

[env]
DEFMT_LOG = "trace"

[unstable]
build-std = ["core"]
build-std-features = ["panic_immediate_abort"]
